import img_quote_snap from "../../assets/images/img_quote_snap.png.png";

export const listPartnerApp = [
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: false,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: false,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: false,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 
    {
        title: "Request a Quote ‑ Hide Price",
        img: img_quote_snap,
        star: 4.9,
        numberReview: 340,
        desc: "For anyone who needs to hide price & request a quote form",
        isBfs: true,
    }, 

];